### ISSUE TITLE
C# Dictionaries - not supported?

### ISSUE THREAD

**Issue by CRidge** [KevinDockx/JsonPatch#69] opened 2017-05-26 06:41 UTC
Hi,

I've been trying to work with models which looks similar to this:

`{
  "101": "Something",
  "102": "Something else",
  "109": "Something else yet again
}`

My C# model maps this to a Dictionary<int, string>. Am I correct when I say this isn't supported with your library? The keys in the dictionary are dynamic, so there's no option to create a model type which matches these. 

Edit: Just to clarify, I'm trying to apply a patch in C# using this model, which I haven't been able to make work. The same patch applied in JS works as expected.

**Comment by mtzaldo** [comment] 2017-06-04 16:33
It doesn't make sense to try to do a json patch to this kind of schema. The scenario I can  think you can use this is if  "101, 102" are keys that hold the reference to the object (kind of primary key). If this is the case I suggest that you try to patch the referenced object...

{ "101" : { name: "", address: "" }, "102": { name: "", address: "" } } ...

So you pass the id/key as a param in the url (101, 102), and then patch the object...

If this is not the case, json patch won't serve your purpose... just do a PUT with the id/key and pass the string and update the referenced string...

**Comment by KevinDockx** [comment] 2017-07-04 12:23
Seems like #58 - closing for now.  If anyone wants to help out on #58, feel free ;-)

**Comment by mtzaldo** [comment] 2017-07-08 16:58
@CRidge I know that the issue is closed, but I gave it a re thought about this, and I was doing a project that needed to convert from a plain object to a JsonPatchDocument. I create a gist where this is being implemented. I hope is not too late for this. It uses Newtonsoft and JsonPatchDocument. Right now it appends the "replace" action only, but you can refactor to accept any action. I tested this with a c# dictionary and it works. I hope it helps.

<script src="https://gist.github.com/mtzaldo/1175ab50a8d5ae66fdc184ba7d39863f.js"></script>

**Comment by CRidge** [comment] 2017-07-17 07:21
@mtzaldo I might be wrong, but I think this solves a problem we've already solved: The generation of the patch document. The problem we had, was applying the patch in C# when the model was using a dictionary.

**Comment by KevinDockx** [comment] 2017-07-17 10:30
There is support for dictionaries in Microsoft.AspNetCore.JsonPatch.  Ideally, that support should be backported into Marvin.JsonPatch (see issue #58).  It's been on the backlog for a while, because porting that change back into this library = a complete rework of the current iterative logic to the visitor pattern.  It's the better approach, obviously, but it's also a lot more work than what I've got time for currently :-(

**Comment by mtzaldo** [comment] 2017-07-18 12:09
@CRidge the gist that i put is an example how an instatiated obj can be translated into a json patch. The patched doc is being generated from the properties automatically

@kevindockx if you have more information about it, and a resource I can read, I can throw some time and work on it. Thanks

**Comment by KevinDockx** [comment] 2017-11-02 12:27
This is now supported.

**Closed by KevinDockx** 2017-11-02 12:27 UTC
